sudo: false
language: python
cache:
  directories:
  - ".benchmarks"
branches:
  only:
  - master
before_install:
- pip install --upgrade pip setuptools wheel
stages:
- quick_test
- test
- name: deploy
  if: type = push AND branch = master
matrix:
  include:
  - stage: quick_test
    os: linux
    env: NAME=misc
    python: '3.6'
    install: skip
    script: check/misc
  - stage: quick_test
    os: linux
    env: NAME=pytest-changed-files
    python: '3.6'
    install:
    - dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh
    script: check/pytest-changed-files
  - stage: quick_test
    os: linux
    env: NAME=format
    python: '3.6'
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep yapf | xargs pip install
    script: check/format-incremental
  - stage: quick_test
    os: linux
    env: NAME=mypy
    python: '3.6'
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install
    script: check/mypy
  - stage: test
    os: windows
    env: NAME=pytest (Windows)
    language: sh
    python: '3.7.3'
    before_install:
      - choco install python --version 3.7.3
      - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
    install:
      - python -m pip install -r requirements.txt
      - python -m pip install -r cirq/contrib/contrib-requirements.txt
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --benchmark-skip --actually-quiet
  - stage: test
    os: linux
    env: NAME=pytest-and-incremental-coverage
    python: '3.6'
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install -r cirq/contrib/contrib-requirements.txt
    - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest-and-incremental-coverage master --actually-quiet
  - stage: test
    os: linux
    env: NAME=build-docs
    python: '3.7'
    install:
      - python -m pip install -r requirements.txt
      - python -m pip install -r cirq/contrib/contrib-requirements.txt
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - sudo apt-get install pandoc
    script: dev_tools/build-docs.sh
  - stage: test
    os: osx
    env: NAME=pytest (macOS)
    python: '3.6'
    language: generic
    install:
      - python3.6 -m venv venv
      - source venv/bin/activate
      - python -m pip install -r requirements.txt
      - python -m pip install -r cirq/contrib/contrib-requirements.txt
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --benchmark-skip
  - stage: test
    os: linux
    env: NAME=pytest (without contrib)
    python: '3.7'
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
    script: check/pytest --ignore=cirq/contrib --benchmark-skip --actually-quiet
  - stage: test
    os: linux
    env: NAME=doctest
    python: '3.6'
    install:
    - python -m pip install -r requirements.txt
    - python -m pip install -r cirq/contrib/contrib-requirements.txt
    script: check/doctest -q
  - stage: test
    os: linux
    env: NAME=pylint
    python: '3.6'
    install:
      - cat dev_tools/conf/pip-list-dev-tools.txt | grep "pylint\|astroid" | grep -v
        "#" | xargs pip install
    script: check/pylint
  - stage: test
    os: linux
    env: NAME=build-protos
    python: '3.6'
    install:
      - python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - wget https://github.com/bazelbuild/bazel/releases/download/0.26.0/bazel_0.26.0-linux-x86_64.deb
      - sudo dpkg -i bazel_0.26.0-linux-x86_64.deb
    script: check/build-protos
  - stage: deploy
    os: linux
    env: NAME=dev-release
    python: '3.7'
    script: export CIRQ_UNSTABLE_VERSION=$(dev_tools/packaging/generate-dev-version-id.sh)
before_deploy:
- echo "Deploying dev version '$CIRQ_UNSTABLE_VERSION'"
deploy:
- provider: pypi
  user: quantumlibdev
  on:
    condition: '"$CIRQ_UNSTABLE_VERSION" == *dev*'
  distributions: bdist_wheel
  password:
    secure: KO3RuwLvjb5/J7akv2v/a9tEIbmErp7El6S+ZfMvDRlx8qpUfav1w4nvSGw6sfn837++2+F2Tb22wbJkjefpFMzg9mOdhFGwtOpiHSOnYlY2mnxVN9XdQnMS7F+8IMFas4J3EhqrlsZxoqyMy122S3pjtE/d6YSG+3YzmCu3rLsFl4EV6I5U8MgWJY8LDFqMIxuxgmEkJfPe5z9Sqqwtneelj39jobg4q1uZc0JD3rkI0hj/uhBvBoTTLQjPiZk3ZIkgkMmPVB8tDGK9eXqVuDK7U1ZoDWvTKNebZ94g46YuKVNY6tEJpgpacti6mMalva6wX8zYpWOrY0PPo34e5d/kfwkttnrMk+sPXJnvn5eM7tEWxF+PHz4ejcLEYpehgdbWksHaUVdPog7UrYXnertHDY42ukxF17JlU9rlf60IXJVmeYHTfB1p8V7Yfllgmfa49yGDnR68Y3iIR9NtT26ZoJnMAkrxvlTgz6poBbTKj+Gyr0pkTHLzniEo3D/C8xeVcD30yZPlXxCojcM4s2dM2h5IiQU//ubptP/TE0idG2AJiooEfGUsXZ+IbN4Zxvkoa4YzYCvYFlr42ZBnv0H5/xZc4uFK6rLcVtysZqWAj3QjVGIUX3G1sxy8ik+RSQun1Dhzov8v5RVtb6aShDWT6l6paAAEwrQNt0T44yo=
