apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: cirq-automerge
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: us-docker.pkg.dev/cirq-infra/cirq/automerge
    docker:
      dockerfile: auto_merge/Dockerfile
    context: dev_tools
deploy:
  kubectl:
    manifests:
    - dev_tools/auto_merge/statefulset.yaml
